// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXkrxKygon9pMUQnpodJW8_r9R2pSLJA8',
    appId: '1:1033631701736:android:e96e8cd4480a6bf053875d',
    messagingSenderId: '1033631701736',
    projectId: 'parking-management-syste-74e6e',
    storageBucket: 'parking-management-syste-74e6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABcRxX1LAlAWchiPcp8Tl3Z4-v3YpFTfk',
    appId: '1:1033631701736:ios:90e77aa116d1887953875d',
    messagingSenderId: '1033631701736',
    projectId: 'parking-management-syste-74e6e',
    storageBucket: 'parking-management-syste-74e6e.appspot.com',
    iosBundleId: 'com.example.parkingManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABcRxX1LAlAWchiPcp8Tl3Z4-v3YpFTfk',
    appId: '1:1033631701736:ios:90e77aa116d1887953875d',
    messagingSenderId: '1033631701736',
    projectId: 'parking-management-syste-74e6e',
    storageBucket: 'parking-management-syste-74e6e.appspot.com',
    iosBundleId: 'com.example.parkingManagementSystem',
  );
}
